// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCmXMRlYLzSsSvohQs1czXWtwTKuN9oAQ0',
    appId: '1:13713518968:web:632fca23d86c0ac10c588d',
    messagingSenderId: '13713518968',
    projectId: 'chatting-app-ad9b0',
    authDomain: 'chatting-app-ad9b0.firebaseapp.com',
    storageBucket: 'chatting-app-ad9b0.firebasestorage.app',
    measurementId: 'G-E08HJ9TQMJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjA6pLesTHIVMPaXFlw7W0-OLKxezDviI',
    appId: '1:13713518968:android:0c51e7687cc912b30c588d',
    messagingSenderId: '13713518968',
    projectId: 'chatting-app-ad9b0',
    storageBucket: 'chatting-app-ad9b0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBGQNOd9STpITxm-KZxMRxDbkAWOv5BSns',
    appId: '1:13713518968:ios:ec207e0798e082010c588d',
    messagingSenderId: '13713518968',
    projectId: 'chatting-app-ad9b0',
    storageBucket: 'chatting-app-ad9b0.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBGQNOd9STpITxm-KZxMRxDbkAWOv5BSns',
    appId: '1:13713518968:ios:ec207e0798e082010c588d',
    messagingSenderId: '13713518968',
    projectId: 'chatting-app-ad9b0',
    storageBucket: 'chatting-app-ad9b0.firebasestorage.app',
    iosBundleId: 'com.example.chattingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCmXMRlYLzSsSvohQs1czXWtwTKuN9oAQ0',
    appId: '1:13713518968:web:6ff6aeb52d2f21cd0c588d',
    messagingSenderId: '13713518968',
    projectId: 'chatting-app-ad9b0',
    authDomain: 'chatting-app-ad9b0.firebaseapp.com',
    storageBucket: 'chatting-app-ad9b0.firebasestorage.app',
    measurementId: 'G-6NTGWD3Y3W',
  );
}
